In [ ]:
print("Привет!")
name=input("Как тебя зовут?")
print("Успешной учёбы, ", name)

Привет!
Как тебя зовут?ааа
Успешной учёбы,  ааа


In [ ]:
age=input("Сколько тебе лет?")
print(age, "? ", "Понятно,", name)

Сколько тебе лет?5
5 ?  Понятно, ааа


In [ ]:
print("\nСколько будет 10 - 3?")
pravotvet = 7
otvet = int(input())
if otvet == pravotvet:
    print("правильный ответ")
else:
    print("вы не правы, попробуйте ещё раз")


Сколько будет 10 - 3?
6
вы не правы, попробуйте ещё раз


In [ ]:
print("Сколько дней в неделе?")
pravotvet=7
otvet=int(input())
if otvet==pravotvet:
    print("правильный ответ")
else:
    print("посмотрите календарь")

Сколько дней в неделе?
5
посмотрите календарь


1.	Создать два произвольных целочисленных “нампаевских” массива mas1 и mas2 из 5 элементов

In [ ]:
import numpy as np
mas1 = np.array([34, 45, 56, 0, -1])
mas2 = np.array([10, 20, 30, 40, 50])
print(mas1, mas2, mas1 + mas2)
print(mas1, mas2, mas1 - mas2)
print(mas1, mas2, mas1 * mas2)

[34 45 56  0 -1] [10 20 30 40 50] [44 65 86 40 49]
[34 45 56  0 -1] [10 20 30 40 50] [ 24  25  26 -40 -51]
[34 45 56  0 -1] [10 20 30 40 50] [ 340  900 1680    0  -50]


2.	Повторить пункт 1 для разных типов данных (целых, вещественных, комплексных, строковых). Выяснить, какие операции работают, а какие нет.  Оставить только работающие операции.

In [ ]:
int1 = np.array([1, 2, 3])
int2 = np.array([4, 5, 6])
float1 = np.array([1.5, 2.5, 3.5])
float2 = np.array([0.5, 1.5, 2.5])
comp1 = np.array([1+2j, 3+4j])
comp2 = np.array([1+1j, 2+2j])
str1 = np.array(['a', 'b'])
str2 = np.array(['x', 'y'])
print(int1 + int2)
print(float1 + float2)
print(comp1 + comp2)
print(str1 + str2)

[5 7 9]
[2. 4. 6.]
[2.+3.j 5.+6.j]
['ax' 'by']


3.	Попробовать поработать с тригонометрическими и другими функциями библиотеки numpy (аргумент — массив)
-создать массивы x1 и x2 из вещественных чисел (одинакового размера!!!)


In [ ]:
x1 = np.array([0.1, 0.2, 0.3, 0.4, 0.5])
x2 = np.array([0.5, 0.4, 0.3, 0.2, 0.1])
y = np.sin(x1) + np.cos(x2)
print(y)

[0.97741598 1.11973032 1.2508567  1.36948492 1.4744297 ]


4.	Создать:
a.	 массив mas0, состоящий из 6 нулей
b.	массив mas1 из 20 единиц


In [ ]:
mas0 = np.zeros(6)
print(mas0)

[0. 0. 0. 0. 0. 0.]


In [ ]:
mas1 = np.ones(20)
print(mas1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


5.	Обращение к отдельным элементам массива  индексация (можно просто перечислить элементы).
a.	 Создать массив A из 8 целых чисел (отрицательных и положительных). Распечатать элементы массива в обратном порядке (можно A[-1], A[-2],...)
b.	Найти сумму всех положительных элементов массива A.
c.	Создать массив, состоящий из строк (“январь“, “февраль“, “март“,...). Обращаясь к элементам массива, распечатать весенние месяцы.


In [ ]:
A = np.array([-5, 3, -2, 7, -1, 4, -3, 8])
print(A[-1], A[-2], A[-3], A[-4], A[-5], A[-6], A[-7], A[-8])

8 -3 4 -1 7 -2 3 -5


In [ ]:
A = np.array([-5, 3, -2, 7, -1, 4, -3, 8])
print(np.sum(A[A > 0]))

22


In [ ]:
months = np.array(["январь", "февраль", "март", "апрель", "май", "июнь"])
print(months[2], months[3], months[4])

март апрель май


Часть 2  Работа аэропорта NNN

1.	Создать два массива Numpy с данными о работе аэропорта NNN за n дней (n=30 - месяц)  — КОЛИЧЕСТВО УЛЕТЕВШИХ САМОЛЁТОВ (ВЫЛЕТ) и КОЛИЧЕСТВО ПРИНЯТЫХ САМОЛЁТОВ (ПРИЛЁТ) (имена массивов задать произвольные — латиница). Можно данные задать вручную, а можно использовать генерацию случайных чисел. Распечатать массивы.

In [ ]:
np.random.seed(42)
n = 30
v = np.random.randint(5, 30, n)
p = np.random.randint(5, 25, n)
print(v)
print(p)

[11 24 19 15 12 25 11 23 27 15 15 28 25  8 12 28  7 26 25  6 28 16 10  6
 25  5 16 26 16 29]
[21 14 20 19 19 23 16 24  7  9 23 11 13 11 22  8 18 22 13  6 24 19 11 16
 12 19  7 18 21  8]


2.	Создать третий массив (из первых двух), содержащий информацию об общем количестве рейсов за каждый день.

In [ ]:
o = v + p
print(o)

[32 38 39 34 31 48 27 47 34 24 38 39 38 19 34 36 25 48 38 12 52 35 21 22
 37 24 23 44 37 37]


3.	Найти максимальные и минимальные значения для всех трёх массивов и распечатать с пояснениями (print) (функции и/или методы).

In [ ]:
print(np.max(v), np.min(v))
print(np.max(p), np.min(p))
print(np.max(o), np.min(o))


29 5
24 6
52 12


4.	Оценить средние, медианы, дисперсии, стандартные отклонения и распечатать (функции и/или методы).

In [ ]:
print(np.mean(v), np.median(v), np.var(v), np.std(v))
print(np.mean(p), np.median(p), np.var(p), np.std(p))
print(np.mean(o), np.median(o), np.var(o), np.std(o))

17.966666666666665 16.0 61.29888888888889 7.829360694775078
15.8 17.0 31.960000000000004 5.653317610041029
33.766666666666666 35.5 87.1788888888889 9.336963579713101


5.	Выяснить, в какую половину месяца было больше суммарное количество рейсов (работаем с третьим массивом  срез+функция/метод+if).

In [ ]:
if np.sum(o[:15]) > np.sum(o[15:]):
    print("первая половина")
else:
    print("вторая половина")

первая половина


6.	Распечатать количество ПРИЛЁТОВ для суббот (считаем, что месяц начинается с понедельника)  используем срез.

In [ ]:
print(p[5], p[12], p[19], p[26])

23 13 6 7


7.	Распечатать данные о ВЫЛЕТАХ  (границы можно скорректировать, ориентируясь на свои данные)
a.	когда их было больше 10
b.	когда их было больше 10, но меньше 50


In [ ]:
print(v[v > 10])

[11 24 19 15 12 25 11 23 27 15 15 28 25 12 28 26 25 28 16 25 16 26 16 29]


In [ ]:
print(v[(v > 10) & (v < 50)])

[11 24 19 15 12 25 11 23 27 15 15 28 25 12 28 26 25 28 16 25 16 26 16 29]


Часть 3

In [ ]:
np.random.seed(123)
A = np.random.randint(1, 11, size=(3, 3))
print(A)

[[ 3  3  7]
 [ 2  4 10]
 [ 7  2  1]]


In [ ]:
print(np.sum(A[A % 2 == 0]))

18


In [ ]:
B = np.dot(np.dot(A, A.T), np.linalg.inv(np.dot(A, A.T)))
print(B)

[[ 1.00000000e+00  8.88178420e-15 -1.63424829e-13]
 [ 5.68434189e-13  1.00000000e+00 -5.68434189e-14]
 [ 2.91322522e-13  1.24344979e-14  1.00000000e+00]]


In [ ]:
print(np.linalg.det(B))

1.0000000000007816


In [ ]:
M = np.zeros((3, 3))
for i in range(3):
    for j in range(3):
        sub = np.delete(np.delete(A, i, axis=0), j, axis=1)
        M[i, j] = np.linalg.det(sub)
print(M)

[[-16. -68. -24.]
 [-11. -46. -15.]
 [  2.  16.   6.]]
