In [ ]:
import numpy as np

delivery_time = np.array([35, 42, 28, 51, 39, 63, 31, 45])

order_price = np.array([1200, 3500, 800, 4200, 1900, 5600, 1500, 2800])

items_count = np.array([2, 5, 1, 7, 3, 8, 2, 4])


1) shape

In [ ]:
print(delivery_time.shape)
print(order_price.shape)
print(items_count.shape)

(8,)
(8,)
(8,)


1) ndim

In [ ]:
print(delivery_time.ndim)
print(order_price.ndim)
print(items_count.ndim)

1
1
1


1) size

In [ ]:
print(delivery_time.size)
print(order_price.size)
print(items_count.size)

8
8
8


3) Проверьте с помощью питон, что все три массива содержат одинаковое количество наблюдений

In [ ]:
n = delivery_time.size
if (len(order_price) == n) and (len(items_count) == n):
  print("одинаковое количество наблюдений")



одинаковое количество наблюдений


Объедините данные в единую матрицу orders.
Каждая строка должна соответствовать одному заказу, а столбцы должны содержать:
1. время доставки;
2. стоимость заказа;
3. количество товаров.

In [ ]:
orders = np.array ([
    [35, 1200, 2],
    [42, 3500, 5],
    [28, 800, 1],
    [51, 4200, 7],
    [39, 1900, 3],
    [63, 5600, 8],
    [31, 1500, 2],
    [45, 2800, 4]
])

1. Выведите orders.shape.

In [ ]:
print(orders.shape)

(8, 3)


С помощью индексации получите:
◦ данные первого заказа;
◦ время доставки всех заказов;
◦ стоимость всех заказов;
◦ количество товаров в шестом заказе.


In [ ]:
print(orders[0])

time_delivery_sum = orders.sum(axis=0)[0]
print(time_delivery_sum)

cost_all_sum = orders.sum(axis=0)[1]
print(cost_all_sum)

print(orders[7][2])

[  35 1200    2]
334
21500
4


С помощью срезов получите:
◦ все заказы начиная с третьего;
◦ первые пять заказов и первые два признака.

In [ ]:
print(orders[2:])


firs_del = orders[:4]
two_sign = firs_del[:, [0, 1]]

print(two_sign)

[[  28  800    1]
 [  51 4200    7]
 [  39 1900    3]
 [  63 5600    8]
 [  31 1500    2]
 [  45 2800    4]]
[[  35 1200]
 [  42 3500]
 [  28  800]
 [  51 4200]]


1. Измените первый элемент delivery на 1000.

In [ ]:
delivery = orders[:, 0]
print(delivery)

delivery[0] = 1000
print(orders)

[35 42 28 51 39 63 31 45]
[[1000 1200    2]
 [  42 3500    5]
 [  28  800    1]
 [  51 4200    7]
 [  39 1900    3]
 [  63 5600    8]
 [  31 1500    2]
 [  45 2800    4]]


Восстановите исходную матрицу orders

In [ ]:
orders = np.array([
    [35, 1200, 2],
    [42, 3500, 5],
    [28, 800, 1],
    [51, 4200, 7],
    [39, 1900, 3],
    [63, 5600, 8],
    [31, 1500, 2],
    [45, 2800, 4]
])
print(orders)

5. Создайте независимую копию, Измените первый элемент delivery_copy.
7. Снова выведите orders

In [ ]:
delivery_copy = orders[:, 0].copy()
delivery_copy[0] = 1000

print(delivery_copy)
print(orders)

[1000   42   28   51   39   63   31   45]
[[1000 1200    2]
 [  42 3500    5]
 [  28  800    1]
 [  51 4200    7]
 [  39 1900    3]
 [  63 5600    8]
 [  31 1500    2]
 [  45 2800    4]]


Задание 1.4. Фильтрация с помощью булевых масок

1. Создайте булеву маску для поиска заказов с временем доставки больше 45 минут.
2. Выведите маску.
3. Используйте маску для получения времени доставки проблемных заказов.
4. Определите количество таких заказов.
5. Рассчитайте среднее время доставки для этой группы

In [ ]:
delivery_time = np.array([35, 42, 28, 51, 39, 63, 31, 45])

mask = delivery_time > 45
print(mask)

problem_deliveries = delivery_time[mask]
print(problem_deliveries)

count_problem = problem_deliveries.size
print(count_problem)

mean_problem = problem_deliveries.mean()
print(mean_problem)

[False False False  True False  True False False]
[51 63]
2
57.0


Задание 1.5. Фильтрация по нескольким условиям

1. Создайте единую булеву маску, учитывающую оба условия.
2. Получите стоимость подходящих заказов.
3. Получите время доставки этих заказов.
4. Рассчитайте среднее время доставки выбранной группы.

In [ ]:
order_price = np.array([1200, 3500, 800, 4200, 1900, 5600, 1500, 2800])
items_count = np.array([2, 5, 1, 7, 3, 8, 2, 4])
delivery_time = np.array([35, 42, 28, 51, 39, 63, 31, 45])

mask = (order_price > 3000) & (items_count > 4)
print(mask)

selected_prices = order_price[mask]
selected_deliveries = delivery_time[mask]

print(selected_prices)
print(selected_deliveries)
print(selected_deliveries.mean())

Задание 2.1. Влияние выбросов на статистические
показатели

1. Рассчитайте:
◦ среднее арифметическое;
◦ медиану.
2. Добавьте в выборку один аномальный результат — доставку продолжительностью
1000 минут:
delivery_time_corrupted = np.array([8, 9, 10, 11, 12, 1000])
3. Повторно рассчитайте среднее и медиану.
4. Сравните результаты до и после появления выброса.


In [ ]:
delivery_time = np.array([8, 9, 10, 11, 12])

mean_clean = delivery_time.mean()
median_clean = np.median(delivery_time)
print(mean_clean)
print(median_clean)

delivery_time_corrupted = np.array([8, 9, 10, 11, 12, 1000])

mean_corrupted = delivery_time_corrupted.mean()
median_corrupted = np.median(delivery_time_corrupted)
print(mean_corrupted)
print(median_corrupted)

print(mean_corrupted - mean_clean)
print(median_corrupted - median_clean)

10.0
10.0
175.0
10.5
165.0
0.5


Задание 2.2. Процентили и SLA

1. Рассчитайте:
◦ среднее значение;
◦ стандартное отклонение;
◦ медиану.
2. Рассчитайте следующие процентили:
p50
p90
p95
p99
используя np.quantile().

In [ ]:
np.random.seed(42)
delivery_simulated = np.random.normal(loc=30, scale=5, size=1000)

mean_sim = delivery_simulated.mean()
std_sim = delivery_simulated.std()
median_sim = np.median(delivery_simulated)

print(mean_sim)
print(std_sim)
print(median_sim)

p50, p90, p95, p99 = np.quantile(delivery_simulated, [0.50, 0.90, 0.95, 0.99])
print(p50)
print(p90)
print(p95)
print(p99)

print(p90 <= 40)

30.096660279111628
4.893631038736771
30.12650306117444
30.12650306117444
36.52822600933569
38.38486264207573
41.57984750401471
True


SlA выполняется, 90 - времени доставки меньше 40 минут, 95 и 99 больше чем 40, значит в срок не попадают. То есть если контролировать и 95, то тогда сроки можно уместить в большинство

Задание 2.3. Разброс и предсказуемость

Для каждой службы рассчитайте:
• среднее;
• медиану;
• стандартное отклонение;
• 90-й процентиль.
При расчёте стандартного отклонения с помощью np.std() используйте стандартное
значение ddof=0.

In [ ]:
service_A = np.array([28, 29, 30, 31, 32])
service_B = np.array([15, 20, 30, 40, 45])

for name, s in [("A", service_A), ("B", service_B)]:
    print(name)
    print(s.mean())
    print(np.median(s))
    print(np.std(s))
    print(np.quantile(s, 0.90))

A
30.0
30.0
1.4142135623730951
31.6
B
30.0
30.0
11.40175425099138
43.0


Задание 2.4. Корреляция

1. Рассчитайте коэффициент корреляции Пирсона между items и
delivery_time_correlated с помощью np.corrcoef().
2. Извлеките коэффициент r.
3. Определите:
◦ направление связи;
◦ силу линейной связи.
4. Сформулируйте возможное объяснение наблюдаемой зависимости с точки зрения
работы склада и доставки.


In [ ]:
np.random.seed(42)
items = np.random.randint(1, 10, 100)
delivery_time_correlated = (
    20
    + 3 * items
    + np.random.normal(0, 3, 100)
)

corr_matrix = np.corrcoef(items, delivery_time_correlated)
r = corr_matrix[0, 1]
print(corr_matrix)
print(r)

[[1.         0.93432937]
 [0.93432937 1.        ]]
0.9343293664033213


Задание 2.5. Корреляция и скрытые факторы

Высокая корреляция не доказывает наличие причинно-следственной связи, потому что идёт фиксация только совместного изменения двух виличин, без учёта направления влияния и т.д. На оба показателя могут влиять время года. Наблюдаемая корреляция происходит по принципу, если на улице жарко, то люди чаще покупают мороженое, а также купаются, из-за чего несчастные случаи происходят чаще. Ложныя корреляция в появлении смартфонов и плохого зрения, вообще мир поменялся вокруг и время проведённое перед экраном увеличилось, но в этом не виноваты сами технологии.

Блок 3. Bootstrap и статистические
гипотезы

Задание 3.1. Bootstrap и доверительный интервал

1. Рассчитайте среднее значение исходной выборки.
2. Реализуйте Bootstrap с количеством итераций:
B = 5000
На каждой итерации:
• сформируйте выборку такого же размера, как x;
• используйте выборку с возвращением;
• рассчитайте её среднее;
• сохраните результат.
Для формирования Bootstrap-выборки используйте:
np.random.choice()
3. Получите центральный 95%-й доверительный интервал для среднего с помощью:
np.quantile()
Используйте квантили:
0.025
0.975
4. Выведите полученный доверительный интервал.

In [ ]:
x = np.array([28, 31, 29, 45, 32, 30])
print(x.mean())

B = 5000
boot_means = np.empty(B)

np.random.seed(42)
for i in range(B):
    sample = np.random.choice(x, size=x.size, replace=True)
    boot_means[i] = sample.mean()

ci_low, ci_high = np.quantile(boot_means, [0.025, 0.975])
print(ci_low)
print(ci_high)

32.5
29.166666666666668
37.666666666666664


Задание 3.2. Формулировка гипотез и ошибки I и II рода

1. Сформулируйте нулевую гипотезу H_0
2. Сформулируйте альтернативную гипотезу H_1.
3. Объясните применительно к этому эксперименту:
◦ что означает ошибка I рода;
◦ что означает ошибка II рода.
4. Укажите, какая ошибка соответствует:
◦ ложной тревоге;
◦ пропущенному эффекту.

Нулевая гипотеза H₀: \mu_A = \mu_B — новый алгоритм не меняет среднее время доставки. Альтернативная гипотеза H₁: \mu_B < \mu_A — новый алгоритм уменьшает среднее время доставки. Ошибка I рода — отвергнуть H₀, когда она верна, то есть решить, что алгоритм улучшил доставку, хотя эффекта нет. Ошибка II рода — не отвергнуть H₀, когда она неверна, то есть не заметить реальное улучшение. Ложная тревога соответствует ошибке I рода, пропущенный эффект — ошибке II рода. В ситуации с эксплуатацией за 5 млн руб./год: если алгоритм не улучшает доставку, а мы его внедрили (ошибка I рода), деньги потрачены зря. Значит, к прямым напрасным расходам приводит ошибка I рода.

Задание 3.3. p-value и принятие решения

1. Дайте определение p-value.
2. Объясните, почему утверждение:
«p-value = 0.001 означает, что вероятность истинности нулевой гипотезы равна 0.1%»
является неверным.
3. Определите, является ли результат статистически значимым при $\alpha = 0.05$.
Ситуация для анализа
Предположим, эксперимент проведён на 1 000 000 пользователей.
Новый алгоритм уменьшил среднее время доставки всего на 3 секунды.
При этом статистический критерий дал:
p-value = 0.001
Эксплуатация нового алгоритма стоит компании 5 млн рублей в год.
Вопросы
1. Является ли результат статистически значимым?
2. Достаточно ли одного p-value для принятия решения о внедрении?
3. Почему статистическая значимость не обязательно означает практическую или бизнесзначимость?
4. Какие дополнительные показатели необходимо учитывать перед раскаткой алгоритма
на всех пользователей?
Итоговый продуктовый вывод
Представьте, что вы отвечаете за принятие решения о внедрении алгоритма.
Сформулируйте итоговую рекомендацию и обоснуйте её с использованием трёх
составляющих принятия решения:
1. Статистическая значимость — насколько убедительны данные с точки зрения
статистического критерия.
2. Размер и практическая значимость эффекта — насколько изменение существенно
для пользователя и продукта.
3. Экономическая целесообразность — превышает ли ожидаемый эффект затраты,
риски и стоимость эксплуатации решения.

p-value это вероятность увидеть такой результат, если на самом деле никакого эффекта нет то есть H₀ верна, а мы всё равно получили то что получили
Утверждение что p-value = 0.001 значит H₀ верна с вероятностью 0.1 процента неправильное, потому что p-value говорит про данные, а не про саму гипотезу
При α = 0.05 результат значим так как 0.001 меньше 0.05 но в примере с миллионом пользователей и улучшением всего на 3 секунды эффект есть, но он крошечный на большой выборке даже 3 секунды становятся значимыми, статистика это ловит а человек нет
Поэтому одного p-value мало нужно смотреть размер эффекта 3 секунды это вообще заметно скорее нет деньги 5 млн в год на алгоритм ради 3 секунд не окупится побочные эффекты удержание NPS хвост распределения p90 p95 риски поддержку
Не внедрять сначала проверить есть ли сегменты где эффект реально большой, и посмотреть что с p90 и p95 если выгода меньше затрат смысла нет, даже если p-value красивый



Итоговый вопрос лабораторной работы


Представьте, что вы получили набор данных о работе интернет-магазина.
Среднее время доставки уменьшилось после изменения алгоритма, но одновременно:
• вырос разброс времени доставки;
• p90 практически не изменился;
• p95 увеличился;
• статистический тест показал p-value < 0.05.
Сформулируйте, какие дополнительные вопросы вы зададите перед тем, как рекомендовать
внедрение изменения на всех пользователей.
В ответе отдельно рассмотрите:
• качество данных;
• размер эффекта;
• распределение результатов;
• выбросы;
• процентили;
• статистическую значимость;
• практическую значимость;
• бизнес-эффект.


Перед внедрением изменения на всех пользователей я задам следующие вопросы.
Качество данных: сопоставимы ли контрольная и тестовая группы по составу (устройства, география, время суток), не было ли изменений в сборе данных во время эксперимента, нет ли пропусков и аномалий в обеих группах.
Размер эффекта: на сколько именно уменьшилось среднее время и насколько это значимо для пользователя, в каких сегментах эффект максимальный, а в каких — нулевой или отрицательный.
Распределение результатов: как изменилась форма распределения, не стало ли оно бимодальным, не ухудшилось ли обслуживание части клиентов.
Выбросы: появились ли новые экстремальные значения, не связаны ли они с ошибками логистики или данными.
Процентили: почему p90 не изменился, а p95 вырос, кто именно пострадал — «длинный хвост», как изменение повлияет на SLA и репутацию.
Статистическая значимость: p < 0.05, но какой размер выборки и мощность теста, устойчив ли результат к разным методам анализа.
Практическая значимость: заметит ли пользователь разницу, стоит ли выигрыш в среднем ухудшения для части клиентов.
Бизнес-эффект: как изменение повлияет на удержание, NPS, повторные заказы, окупятся ли затраты на внедрение и поддержку.
Рекомендовать внедрение можно только после того, как мы убедимся, что ухудшение хвоста (p95) контролируемо, выигрыш в среднем не достигается за счёт ухудшения сервиса для части клиентов, а экономический эффект превышает затраты